### ISSUE TITLE
不知道怎么说

### ISSUE THREAD

**Issue by LHC-kali** [Gourob-Dev/ultimate_termux_setup#2]
![SRC_20201014_222927](https://user-images.githubusercontent.com/65726352/96003372-c045f880-0e6c-11eb-9a9b-1eec34254a3e.png)
这是？

**Comment by Gourob-Dev** [comment]
Sorry I'm also having some issues with the code I'll debug the installation script soon.

**Comment by Gourob-Dev** [comment]
The code has been debugged please try it.

**Comment by LHC-kali** [comment]
Thank you for your reference.

在 2020年10月18日星期日，Gourob Dev <notifications@github.com> 写道：
